- name: Set ipv4.ip_forward 1
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes


#- name: Install apt-packages
#  apt:
#      name: "{{ item }}"
#      state: present
#      update_cache: yes
#      cache_valid_time: 86400
#  with_items:
#      - bridge-utils
#      - libnm-glib-dev
#      - python-dbus


#- name: Create bridge
#  blockinfile:
#      dest: /etc/network/interfaces
#      insertafter: '^iface lo inet loopback'
#      content: |
#          auto lxd_bridge
#          iface lxd_bridge inet static
#              address 10.10.10.1
#              netmask 255.255.255.0
#              network 10.10.10.0
#              broadcast 10.10.10.255
#              gateway 192.168.0.1
#              bridge_stp off
#              bridge_maxwait 0

#- name: Create bridge
#  nmcli:
#      type: bridge
#      conn_name: br0
#      ifname: br0
#      state: present 

#- name: Restart networking
#  service:
#      name: network-manager
#      state: restarted

- name: Install LXD
  apt:
      name: "{{ item }}"
      state: latest
      update_cache: yes
      cache_valid_time: 3600
  with_items:
      - lxd
      - lxd-client
      - zfsutils-linux


#- name: Copy LXD init file
#  copy:
#      src: lxd.yaml
#      dest: ~/lxd.yaml


- name: Check pool
  shell: zpool status -v tank
  register: zpool_check
  failed_when: False
  changed_when: False


- name: Copy lxd-bridge init file
  copy:
      src: lxd-bridge
      dest: /etc/default/lxd-bridge

- name: Init LXD
  shell: >
    lxd init --auto 
    --storage-backend zfs 
    --storage-pool tank 
    --storage-create-loop 20 
    --network-address 0.0.0.0 
    --network-port 8443 
    --trust-password password
  when: zpool_check.rc == 1

  
- name: Create a profile
  lxd_profile:
      name: ci_profile
      state: present
      config: {}
      description: ci profile
      devices:
          eth0:
              nictype: bridged
              parent: lxdbr0
              type: nic


- name: Create a started container
  lxd_container:
    name: c1
    state: started
    source:
      type: image
      mode: pull
      server: https://images.linuxcontainers.org
      protocol: lxd
      alias: ubuntu/xenial/amd64
    profiles: ["ci_profile"]
    wait_for_ipv4_addresses: true
  register: containers


- debug: var=containers

- name: Set container password
  shell: lxc exec c1 echo root:password | chpasswd
  when: containers.changed

- name: Install SSH in Container
  shell: lxc exec c1 apt install -y open-ssh
  when: containers.changed

- name: Restart SSH service in Container
  shell: lxc exec c1 systemctl restart sshd
  when: containers.changed



